[tox]
envlist =
    flake8
    py{38,39,310}-cms311
    py{310,311,312}-cms{41,50}

skip_missing_interpreters = True

[testenv]
passenv =
    CI
    TRAVIS_BUILD_NUMBER
    TRAVIS_PULL_REQUEST
    TRAVIS_REPO_SLUG
    TRAVIS_JOB_NUMBER
whitelist_externals =
    sh
    sleep
commands =
    {envpython} --version
    - coverage erase
    coverage run test_settings.py
    - coverage report
deps =
    cms311: django-treebeard~=4.0
    cms311: django-cms~=3.11
    cms41: django-treebeard~=4.0
    cms41: django-cms~=4.1
    cms41: django~=4.1
    cms50: django-cms~=5.0
    cms50: django~=5.2
    -r{toxinidir}/test_requirements.txt

[testenv:flake8]
deps = flake8
commands = flake8

[flake8]
ignore = E251,E128
exclude = aldryn_categories/migrations/*,docs/conf.py,build/*
max-line-length = 120

[testenv:isort]
deps = isort
commands = isort -c -rc -df aldryn_categories
skip_install = true
