# Generated by Django 5.2.13 on 2026-04-13 06:17

import djangocms_attributes_field.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "aldryn_categories",
            "0005_alter_category_id_alter_categorytranslation_id_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="attributes",
            field=djangocms_attributes_field.fields.AttributesField(
                blank=True, default=dict, verbose_name="Attributes"
            ),
        ),
    ]
